### PR TITLE
Fix IngressClasses example

### PR DESCRIPTION
**Pull request by kmadel**
The IngressClasses summary is incorrect and the example is misleading.

### CODE REVIEW

**Comment by Piotr1215** [comment]
Could you please [allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so I can help  you with `vale`?

**Comment by kmadel** [comment]
> Could you please [allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so I can help you with `vale`?

I already see that "Allow edits and access to secrets by maintainers" is checked. What else needs to be done to allow edits?

**Comment by Piotr1215** [comment]
I'm still not able to push my changes:

```bash
➜ git push --force-with-lease fork quick-start-explore-ingress-classes-fix
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:kmadel/vcluster-docs.git
 ! [remote rejected]   quick-start-explore-ingress-classes-fix -> quick-start-explore-ingress-classes-fix (permission denied)
error: failed to push some refs to 'github.com:kmadel/vcluster-docs.git'
```

This worked [on another PR](https://github.com/loft-sh/vcluster-docs/pull/314), double-check that settings are applied (toggle them maybe), you can also add me as collaborator to your fork.

**Comment by kmadel** [comment]
I toggled the Allow Edits settings and added you as a contributor to my fork.

**Review by deniseschannon — APPROVED** [review]

**Review by Piotr1215 — APPROVED** [review]

**Pull request merged**
